### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by mvastola** [garryyao/jsongrep#1]
When I try to run `jsongrep` on the command line, I always get the following error:
```javascript
/usr/local/lib/node_modules/jsongrep/cli.js:5
let query = process.argv[2] || '$';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Here is my version info for npm (running `npm version`):
```javascript
{ npm: '3.5.2',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '55.1',
  modules: '46',
  node: '4.2.6',
  openssl: '1.0.2g-fips',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

Interestingly, I'm noticing that running `npm show jsongrep` gives me the following:
```javascript
{ name: 'jsongrep',
  description: 'Mining values in structural JSON, like grep using JSONPath',
  'dist-tags': { latest: '0.0.4' },
  versions: [ '0.0.3', '0.0.4' ],
  maintainers: [ 'garryyao <yaojun85@gmail.com>' ],
  time:
   { modified: '2016-12-01T08:27:38.549Z',
     created: '2016-12-01T08:21:40.814Z',
     '0.0.3': '2016-12-01T08:21:40.814Z',
     '0.0.4': '2016-12-01T08:27:38.549Z' },
  homepage: 'https://github.com/garryyao/jsongrep#readme',
  keywords: [ 'json', 'grep' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/garryyao/jsongrep.git' },
  author: 'garry.yao@ge.com',
  bugs: { url: 'https://github.com/garryyao/jsongrep/issues' },
  license: 'ISC',
  readmeFilename: 'README.md',
  version: '0.0.4',
  bin: { jsongrep: './cli.js' },
  main: 'index.js',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  dependencies:
   { byline: '^5.0.0',
     'json-tokenizer': '^1.0.1',
     'jsonpath-plus': '^0.15.0',
     readline: '^1.3.0' },
  devDependencies: {},
  gitHead: '1da848bb75986efa2ddf645593b9ff280f0db787',
  dist:
   { shasum: '823664e82db874a2cd84b36454675f236538b2af',
     tarball: 'https://registry.npmjs.org/jsongrep/-/jsongrep-0.0.4.tgz' },
  directories: {} }
```

I'm noticing, however, that version 0.0.4 doesn't exist in this repo, nor does any commit with hash `1da848bb75986efa2ddf645593b9ff280f0db787`. The `cli.js` from the `HEAD` of the `master` branch, however, is identical to the version 0.0.4 in npm (even though it is marked as version 0.0.3 here).

**Comment by mvastola** [comment]
Oh, I should have added I'm running Ubuntu Xenial with all the latest packages and the distro's `nodejs`.
Running `dpkg-query -W nodejs` gives me:
```
nodejs  4.2.6~dfsg-1ubuntu4.1
```
